---

- name: "NOTSCORED | 3.3.1 | PATCH | Ensure TCP Wrappers is installed"
  apt:
      name: tcpd
      state: present
  when:
      - ubtu18cis_rule_3_3_1
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_3.3.1
      - tcp_wrapper
      - apt

- name: "NOTSCORED | 3.3.2 | PATCH | Ensure /etc/hosts.allow is configured"
  template:
      src: hosts.allow.j2
      dest: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_3_3_2
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_3.3.2

- name: "NOTSCORED | 3.3.3 | PATCH | Ensure /etc/hosts.deny is configured"
  lineinfile:
      path: /etc/hosts.deny
      regexp: '^(#)?ALL'
      line: 'ALL: ALL'
  when:
      - ubtu18cis_rule_3_3_3
      - not system_is_ec2
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_3.3.3

- name: "SCORED | 3.3.4 | PATCH | Ensure permissions on /etc/hosts.allow are configured"
  file:
      path: /etc/hosts.allow
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_3_3_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - rule_3.3.4
      - permissions

- name: "SCORED | 3.3.5 | PATCH | Ensure permissions on /etc/hosts.deny are configured"
  file:
      path: /etc/hosts.deny
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_3_3_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - rule_3.3.5
      - permissions
