---
- name: "MANUAL | 3.1.1 | PATCH | Disable IPv6"
  lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*(?!.*ipv6\.disable=1)\"[^\"]+)(\".*)'
      line: '\1 ipv6.disable=1\2'
      backrefs: yes
  notify: grub update
  when:
      - ubtu18cis_rule_3_1_1
      - not ubtu18cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - manual
      - patch
      - rule_3.1.1
      - ipv6

- name: "AUTOMATED | 3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "AUTOMATED | 3.1.2 | AUDIT | Ensure wireless interfaces are disabled | Check if nmcli command is available"
        command: dpkg -s network-manager
        args:
            warn: no
        check_mode: false
        changed_when: false
        register: ubtu18cis_nmcli_available
        failed_when: no

      - name: "AUTOMATED | 3.1.2 | AUDIT | Ensure wireless interfaces are disabled | Check if wifi is enabled"
        command: nmcli radio wifi
        register: ubtu18cis_wifi_enabled
        check_mode: false
        changed_when: ubtu18cis_wifi_enabled.stdout != "disabled"
        when: ubtu18cis_nmcli_available.rc == 0

      - name: "AUTOMATED | 3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wifi if enabled"
        command: nmcli radio wifi off
        when: ubtu18cis_wifi_enabled is changed
  when:
      - ubtu18cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_3.1.2
      - wireless

# - name: "SCORED | 3.1.1 | PATCH | Ensure packet redirect sending is disabled"
#   sysctl:
#       name: "{{ item }}"
#       value: '0'
#       sysctl_set: yes
#       state: present
#       reload: yes
#       ignoreerrors: yes
#   with_items:
#       - net.ipv4.conf.all.send_redirects
#       - net.ipv4.conf.default.send_redirects
#   notify: sysctl flush ipv4 route table
#   when:
#       - ubtu18cis_rule_3_1_1
#       - not ubtu18cis_is_router
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_3.1.1
#       - packet_redirect
#       - sysctl

# - name: "SCORED | 3.1.2 | PATCH | Ensure IP forwarding is disabled"
#   block:
#       - name: "SCORED | 3.1.2 | PATCH | Ensure IP forwarding is disabled | IPv4 settings"
#         sysctl:
#             name: net.ipv4.ip_forward
#             value: '0'
#             sysctl_set: yes
#             state: present
#             reload: yes
#             ignoreerrors: yes
#         notify:
#             - sysctl flush ipv4 route table

#       - name: "SCORED | 3.1.2 | PATCH | Ensure IP forwarding is disabled | IPv6 settings"
#         sysctl:
#             name: net.ipv6.conf.all.forwarding
#             value: '0'
#             sysctl_set: yes
#             state: present
#             reload: yes
#             ignoreerrors: yes
#         notify:
#             - sysctl flush ipv6 route table
#   when:
#       - ubtu18cis_rule_3_1_2
#       - not ubtu18cis_is_router
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_3.1.2
#       - ip_forwarding
#       - sysctl