---
- name: "6.1.1 | AUDIT | Audit system file permissions"
  block:
      - name: "6.1.1 | AUDIT | Audit system file permissions | Register package list"
        ansible.builtin.shell: dpkg-query -W -f='${binary:Package}\n'
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_1_packages
        when:
            - not ubtu18cis_manual_audit_dpkg

      - name: "6.1.1 | AUDIT | Audit system file permissions | Audit the packages"
        ansible.builtin.shell: "dpkg --verify {{ item }}"
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_1_packages_audited
        with_items: "{{ ubtu18cis_6_1_1_packages.stdout_lines }}"
        when:
            - not ubtu18cis_manual_audit_dpkg

      - name: "6.1.1 | AUDIT | Audit system file permissions | Merge Package Name And Stdout."
        ansible.builtin.set_fact:
            ubtu18cis_6_1_1_packages_issues: "{{ merged|default({}) | combine( {item.item: item.stdout} ) }}"
        with_items:
            - "{{ ubtu18cis_6_1_1_packages_audited.results }}"
        when:
            - not ubtu18cis_manual_audit_dpkg
            - ubtu18cis_6_1_1_packages is defined
            - item.stdout | length > 0

      - name: "6.1.1 | AUDIT | Audit system file permissions | Audited Check Results."
        ansible.builtin.debug:
            msg:
                - "Warning!! The packages below may not have the correct file permissions."
                - "Please review the list below and make sure they conform to site policies."
                - "{{ ubtu18cis_6_1_1_packages_issues }}"
        when:
            - not ubtu18cis_manual_audit_dpkg

      - name: "6.1.1 | AUDIT | Audit system file permissions | Message out packages results for review"
        ansible.builtin.debug:
            msg:
                - "Warning!! Please validate system file permissions."
                - "You can run dpkg --verify <package name> and if nothing is returned the package is installed correctly"
        when: ubtu18cis_manual_audit_dpkg

      - name: "6.1.1 | AUDIT | Audit system file permissions | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '6.1.1'
  when:
      - ubtu18cis_rule_6_1_1
  tags:
      - level2-server
      - level2-workstation
      - manual
      - audit
      - rule_6.1.1
      - permissions

- name: "6.1.2 | PATCH | Ensure permissions on /etc/passwd are configured"
  ansible.builtin.file:
      path: /etc/passwd
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.2
      - permissions

- name: "6.1.3 | PATCH | Ensure permissions on /etc/passwd- are configured"
  ansible.builtin.file:
      path: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.3
      - permissions

- name: "6.1.4 | PATCH | Ensure permissions on /etc/group are configured"
  ansible.builtin.file:
      path: /etc/group
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.4
      - permissions

- name: "6.1.5 | PATCH | Ensure permissions on /etc/group- are configured"
  ansible.builtin.file:
      path: /etc/group-
      owner: root
      group: root
      mode: 0644
  when:
      - ubtu18cis_rule_6_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.5
      - permissions

- name: "6.1.6 | PATCH | Ensure permissions on /etc/shadow are configured"
  ansible.builtin.file:
      path: /etc/shadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.6
      - permissions

- name: "6.1.7 | PATCH | Ensure permissions on /etc/shadow- are configured"
  ansible.builtin.file:
      path: /etc/shadow-
      owner: root
      group: shadow
      mode: 0600
  when:
      - ubtu18cis_rule_6_1_7
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.7
      - permissions

- name: "6.1.8 | PATCH | Ensure permissions on /etc/gshadow are configured"
  ansible.builtin.file:
      path: /etc/gshadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_8
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.8
      - permissions

- name: "6.1.9 | PATCH | Ensure permissions on /etc/gshadow- are configured"
  ansible.builtin.file:
      path: /etc/gshadow-
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubtu18cis_rule_6_1_9
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.9
      - permissions

- name: "6.1.10 | PATCH | Ensure no world writable files exist"
  block:
      - name: "6.1.10 | PATCH | Ensure no world writable files exist | Get list of world-writable files"
        ansible.builtin.shell: find {{ item.mount }} -xdev -type f -perm -0002
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_10_wwf
        with_items:
            - "{{ ansible_mounts }}"

      - name: "6.1.10 | PATCH | Ensure no world writable files exist | Adjust world-writable files if they exist"
        ansible.builtin.file:
            path: "{{ item }}"
            mode: o-w
        with_items:
            - "{{ ubtu18cis_6_1_10_wwf.results | map(attribute='stdout_lines') | flatten  }}"
        when: ubtu18cis_no_world_write_adjust
  when:
      - ubtu18cis_rule_6_1_10
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.10
      - permissions

- name: "6.1.11 | AUDIT | Ensure no unowned files or directories exist"
  block:
      - name: "6.1.11 | AUDIT | Ensure no unowned files or directories exist | Finding all unowned files or directories"
        ansible.builtin.shell: find "{{ item.mount }}" -xdev -nouser
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu18cis_6_1_11_audit
        loop: "{{ ansible_mounts }}"
        loop_control:
            label: "{{ item.mount }}"
        when: item['device'].startswith('/dev') and not 'bind' in item['options']

      - name: "6.1.11 | AUDIT | Ensure no unowned files or directories exist | set fact"
        ansible.builtin.set_fact:
            ubtu18cis_6_1_11_unowned_files_found: true
        loop: "{{ ubtu18cis_6_1_11_audit.results }}"
        when:
            - item.stdout is defined
            - item.stdout | length > 0

      - name: "6.1.11 | AUDIT | Ensure no unowned files or directories exist | Displaying any unowned files or directories"
        ansible.builtin.debug:
            msg: "Warning!! Missing owner on items in {{ ubtu18cis_6_1_11_audit.results| map(attribute='stdout_lines') | flatten }}"
        when: ubtu18cis_6_1_11_unowned_files_found

      - name: "6.1.11 | AUDIT | Ensure no unowned files or directories exist | warning"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '6.1.11'
        when: ubtu18cis_6_1_11_unowned_files_found
  vars:
      ubtu18cis_6_1_11_unowned_files_found: false
  when:
      - ubtu18cis_rule_6_1_11
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.11
      - permissions

- name: "6.1.12 | AUDIT | Ensure no ungrouped files or directories exist"
  block:
      - name: "6.1.12 | AUDIT | Ensure no ungrouped files or directories exist | Finding all ungrouped files or directories"
        ansible.builtin.shell: find "{{ item.mount }}" -xdev -nogroup
        check_mode: false
        failed_when: false
        changed_when: false
        register: ubtu18cis_6_1_12_audit
        loop: "{{ ansible_mounts }}"
        loop_control:
            label: "{{ item.mount }}"
        when: item['device'].startswith('/dev') and not 'bind' in item['options']

      - name: "6.1.12 | AUDIT | Ensure no ungrouped files or directories exist | set fact"
        ansible.builtin.set_fact:
            ubtu18cis_6_1_12_ungrouped_files_found: true
        loop: "{{ ubtu18cis_6_1_12_audit.results }}"
        when:
            - item.stdout is defined
            - item.stdout | length > 0

      - name: "6.1.12 | AUDIT | Ensure no ungrouped files or directories exist | Displaying any unowned files or directories"
        ansible.builtin.debug:
            msg: "Warning!! Missing owner on items in {{ ubtu18cis_6_1_12_audit.results | map(attribute='stdout_lines') | flatten }}"
        when: ubtu18cis_6_1_12_ungrouped_files_found

      - name: "6.1.12 | AUDIT | Ensure no ungrouped files or directories exist | warning"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '6.1.12'
        when: ubtu18cis_6_1_12_ungrouped_files_found
  vars:
      ubtu18cis_6_1_12_ungrouped_files_found: false
  when:
      - ubtu18cis_rule_6_1_12
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_6.1.12
      - permissions

- name: "6.1.13 | AUDIT | Audit SUID executables"
  block:
      - name: "6.1.13 | AUDIT | Audit SUID executables | Find all SUID executables"
        ansible.builtin.shell: df {{ item.mount }} -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -4000
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_13_suid_perms
        loop: "{{ ansible_mounts }}"
        loop_control:
            label: "{{ item.mount }}"

      - name: "6.1.13 | AUDIT | Audit SUID executables | set fact SUID executables"
        ansible.builtin.set_fact:
            ubtu18cis_6_1_13_suid_found: true
        loop: "{{ ubtu18cis_6_1_13_suid_perms.results }}"
        when: item.stdout | length > 0

      - name: "6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist"
        ansible.builtin.debug:
            msg: "Warning!! SUID on items in {{ ubtu18cis_6_1_13_suid_perms.results | map(attribute='stdout_lines') | flatten }}"
        when: ubtu18cis_6_1_13_suid_found

      - name: "6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist | warning"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '6.1.13'
        when: ubtu18cis_6_1_13_suid_found
  vars:
      ubtu18cis_6_1_13_suid_found: false
  when:
      - ubtu18cis_rule_6_1_13
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_6.1.13
      - permissions

- name: "6.1.14 | AUDIT | Audit SGID executables"
  block:
      - name: "6.1.14 | AUDIT | Audit SGID executables | Find all SGID executables"
        ansible.builtin.shell: df {{ item.mount }} -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000
        changed_when: false
        failed_when: false
        register: ubtu18cis_6_1_14_sgid_perms
        loop: "{{ ansible_mounts }}"
        loop_control:
            label: "{{ item.mount }}"

      - name: "6.1.14 | AUDIT | Audit SGID executables | Set fact SGID executables"
        ansible.builtin.set_fact:
            ubtu18cis_6_1_14_sgid_found: true
        loop: "{{ ubtu18cis_6_1_14_sgid_perms.results }}"
        when: item.stdout | length > 0

      - name: "6.1.14 | AUDIT | Audit SGID executables | Alert SGID executables exist"
        ansible.builtin.debug:
            msg: "Warning!! SGID on items in {{ ubtu18cis_6_1_14_sgid_perms.results | map(attribute='stdout_lines') | flatten }}"  # noqa: jinja[invalid]
        when: ubtu18cis_6_1_14_sgid_found

      - name: "6.1.14 | AUDIT | Audit SGID executables| warning"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '6.1.14'
        when: ubtu18cis_6_1_14_sgid_found
  vars:
      ubtu18cis_6_1_14_sgid_found: false
  when:
      - ubtu18cis_rule_6_1_14
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_6.1.14
      - permissions
