---
- name: "AUTOMATED | 2.2.1 | PATCH | Ensure NIS Client is not installed"
  apt:
      name: nis
      state: absent
  when:
      - ubtu18cis_rule_2_2_1
      - not ubtu18cis_nis_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.1
      - nis

- name: "AUTOMATED | 2.2.2 | PATCH | Ensure rsh client is not installed"
  apt:
      name: rsh-client
      state: absent
  when:
      - ubtu18cis_rule_2_2_2
      - not ubtu18cis_rsh_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.2
      - rsh

- name: "AUTOMATED | 2.2.3 | PATCH | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when:
      - ubtu18cis_rule_2_2_3
      - not ubtu18cis_talk_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.3
      - talk

- name: "AUTOMATED | 2.2.4 | PATCH | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when:
      - ubtu18cis_rule_2_2_4
      - not ubtu18cis_telnet_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.4
      - telnet

- name: "AUTOMATED | 2.2.5 | PATCH | Ensure LDAP client is not installed"
  apt:
      name: ldap-utils
      state: absent
  when:
      - ubtu18cis_rule_2_2_5
      - not ubtu18cis_ldap_clients_required
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.5
      - ldap

- name: "AUTOMATED | 2.2.6 | PATCH | Ensure RPC is not installed"
  apt:
      name: rpcbind
      state: absent
  when:
      - ubtu18cis_rule_2_2_6
      - not ubtu18cis_rpc_server
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_2.2.7
      - rpc
      - services

# all moved to 2.1.x.yml
# - name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use"
#   apt:
#       name: "{{ ubtu18cis_time_sync_tool }}"
#       state: present
#   when:
#       - ubtu18cis_rule_2_2_1_1
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.1.1
#       - chrony

# - name: "NOTSCORED | 2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured"
#   block:
#       - name: "NOTSCORED | 2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set configuration for systemd-timesyncd"
#         lineinfile:
#             path: /etc/systemd/timesyncd.conf
#             regexp: "{{ item.regexp }}"
#             line: "{{ item.line }}"
#             insertafter: "{{ item.insertafter }}"
#         with_items:
#             - { regexp: '^\[Time\]', line: '[Time]', insertafter: EOF }
#             - { regexp: '^#NTP|^NTP', line: 'NTP=0.ubuntu.pool.ntp.org 1.ubuntu.pool.ntp.org 2.ubuntu.pool.ntp.org', insertafter: '\[Time\]' }
#             - { regexp: '^#FallbackNTP|^FallbackNTP', line: 'FallbackNTP=ntp.ubuntu.com 3.ubuntu.pool.ntp.org', insertafter: '\[Time\]' }
#             - { regexp: '^#RootDistanceMaxSec|^RootDistanceMaxSec', line: 'RootDistanceMaxSec=1', insertafter: '\[Time\]'}

#       - name: "NOTSCORED | 2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Start and enable the systemd-timesyncd service"
#         service:
#             name: systemd-timesyncd.service
#             state: started
#             enabled: yes

#       - name: "NOTSCORED | 2.2.1.2 | PATCH | Ensure systemd-timesyncd is configured | Set timedatectl to ntp"
#         command: timedatectl set-ntp true
#   when:
#       - ubtu18cis_rule_2_2_1_2
#   tags:
#       - level1-server
#       - level1-workstation
#       - notscored
#       - patch
#       - rule_2.2.1.2
#       - systemd-timesyncd

# - name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured"
#   block:
#       - name: "SCORED | 2.2.1.3 | AUDIT | Ensure chrony is configured | Check for chrony user"
#         shell: grep chrony /etc/passwd
#         changed_when: false
#         failed_when: false
#         register: ubtu18cis_2_2_1_3_chrony_user_status

#       - name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | Set chrony.conf file"
#         template:
#             src: chrony.conf.j2
#             dest: /etc/chrony/chrony.conf
#             owner: root
#             group: root
#             mode: 0644

#       - name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | Create chrony user"
#         user:
#             name: chrony
#             shell: /usr/sbin/nologin
#             system: true
#         when: ubtu18cis_2_2_1_3_chrony_user_status.stdout != ""

#       - name: "SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured | Set option to use chrony user"
#         lineinfile:
#             path: /etc/default/chrony
#             regexp: '^DAEMON_OPTS'
#             line: 'DAEMON_OPTS="-u chrony"'
#   when:
#       - ubtu18cis_rule_2_2_1_3
#       - ubtu18cis_time_sync_tool == "chrony"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.1.3
#       - chrony

# - name: "SCORED | 2.2.1.4 | PATCH | Ensure ntp is configured"
#   block:
#       - name: "SCORED | 2.2.1.4 | PATCH | Ensure ntp is configured | Set ntp.conf settings"
#         template:
#             src: ntp.conf.j2
#             dest: /etc/ntp.conf
#             owner: root
#             group: root
#             mode: 0644

#       - name: "SCORED | 2.2.1.4 | PATCH | Ensure ntp is configured | Modify sysconfig/ntpd"
#         lineinfile:
#             path: /etc/sysconfig/ntpd
#             regexp: "{{ item.regexp }}"
#             line: "{{ item. line }}"
#             create: yes
#         with_items:
#             - { regexp: '^OPTIONS', line: 'OPTIONS="-u ntp:ntp"'}
#             - { regexp: '^NTPD_OPTIONS', line: 'NTPD_OPTIONS="-u ntp:ntp"' }

#       - name: "SCORED | 2.2.1.4 | PATCH | Ensure ntp is configured | Modify /etc/init.d/npt"
#         lineinfile:
#             path: /etc/init.d/ntp
#             regexp: '^RUNAUSER'
#             line: 'RUNAUSER=npt'
#   when:
#       - ubtu18cis_rule_2_2_1_4
#       - ubtu18cis_time_sync_tool == "ntp"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.1.4
#       - ntp

# - name: "SCORED | 2.2.2 | PATCH | Ensure X Window System is not installed"
#   apt:
#       name: xserver-xorg*
#       state: absent
#   when:
#       - ubtu18cis_rule_2_2_2
#       - not ubtu18cis_desktop_required
#   tags:
#       - level1-server
#       - scored
#       - patch
#       - rule_2.2.2
#       - xwindows

# - name: "SCORED | 2.2.3 | PATCH | Ensure Avahi Server is not enabled"
#   service:
#       name: avahi-daemon
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_3
#       - not ubtu18cis_avahi_server
#       - avahi_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.3
#       - avahi
#       - services

# - name: "SCORED | 2.2.4 | PATCH | Ensure CUPS is not enabled"
#   service:
#       name: cups
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_4
#       - not ubtu18cis_cups_server
#       - cups_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level2-workstation
#       - scored
#       - patch
#       - rule_2.2.4
#       - cups
#       - services

# - name: "SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled"
#   block:
#       - name: "SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled | Disable isc-dhcp-server service"
#         service:
#             name: isc-dhcp-server
#             state: stopped
#             enabled: no
#         when: dhcp_service_status == "loaded"

#       - name: "SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not enabled | Disable isc-dhcp-server6 service"
#         service:
#             name: isc-dhcp-server6
#             state: stopped
#             enabled: no
#         when: dhcp6_service_status == "loaded"
#   when:
#       - ubtu18cis_rule_2_2_5
#       - not ubtu18cis_dhcp_server
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.5
#       - dhcp
#       - services

# - name: "SCORED | 2.2.6 | PATCH | Ensure LDAP server is not enabled"
#   service:
#       name: slapd
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_6
#       - not ubtu18cis_ldap_server
#       - slapd_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.6
#       - ldap
#       - services

# - name: "SCORED | 2.2.7 | PATCH | Ensure NFS and RPC are not enabled"
#   block:
#       - name: "SCORED | 2.2.7 | PATCH | Ensure NFS and RPC are not enabled | Disable NFS service"
#         service:
#             name: nfs-server
#             state: stopped
#             enabled: no
#         when: nfs_service_status.stdout == "loaded"

#       - name: "SCORED | 2.2.7 | PATCH | Ensure NFS and RPC are not enabled | Disable RPC service"
#         service:
#             name: rpcbind
#             state: stopped
#             enabled: no
#         when: rpcbind_service_status.stdout == "loaded"
#   when:
#       - ubtu18cis_rule_2_2_7
#       - not ubtu18cis_nfs_rpc_server
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.7
#       - nfs
#       - rpc
#       - services

# - name: "SCORED | 2.2.8 | PATCH | Ensure DNS Server is not enabled"
#   service:
#       name: bind9
#       status: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_8
#       - not ubtu18cis_dns_server
#       - named_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.8
#       - dns
#       - service

# - name: "SCORED | 2.2.9 | PATCH | Ensure FTP Server is not enabled"
#   service:
#       name: vsftpd
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_9
#       - not ubtu18cis_vsftpd_server
#       - vsftpd_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.9
#       - ftp
#       - service

# - name: "SCORED | 2.2.10 | PATCH | Ensure HTTP server is not enabled"
#   service:
#       name: apache2
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_10
#       - not ubtu18cis_httpd_server
#       - httpd_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.10
#       - httpd
#       - service

# - name: "SCORED | 2.2.11 | PATCH | Ensure email services are not enabled"
#   service:
#       name: dovecot
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_11
#       - not ubtu18cis_dovecot_server
#       - dovecot_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.11
#       - dovecot
#       - service

# - name: "SCORED | 2.2.12 | PATCH | Ensure Samba is not enabled"
#   service:
#       name: smbd
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_12
#       - not ubtu18cis_smb_server
#       - smb_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.12
#       - samba
#       - service

# - name: "SCORED | 2.2.13 | PATCH | Ensure HTTP Proxy Server is not enabled"
#   service:
#       name: squid
#       states: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_13
#       - not ubtu18cis_squid_server
#       - squid_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.13
#       - http_proxy
#       - service

# - name: "SCORED | 2.2.14 | PATCH | Ensure SNMP Server is not enabled"
#   service:
#       name: snmpd
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_14
#       - not ubtu18cis_snmp_server
#       - snmpd_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.14
#       - snmp
#       - service

# - name: "SCORED | 2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
#   lineinfile:
#       path: /etc/postfix/main.cf
#       regexp: '^(#)?inet_interfaces'
#       line: 'inet_interfaces = loopback-only'
#   notify: restart postfix
#   when:
#       - ubtu18cis_rule_2_2_15
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.15
#       - postfix

# - name: "SCORED | 2.2.16 | PATCH | Ensure rsync service is not enabled"
#   service:
#       name: rsync
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_16
#       - not ubtu18cis_rsync_server
#       - rsync_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_2.2.16
#       - rsync

# - name: "SCORED | 2.2.17 | PATCH | Ensure NIS Server is not enabled"
#   service:
#       name: nis
#       state: stopped
#       enabled: no
#   when:
#       - ubtu18cis_rule_2_2_17
#       - not ubtu18cis_nis_server
#       - nis_service_status.stdout == "loaded"
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - rule_2.2.17
#       - nis
#       - service
