---
- name: "SCORED | 2.3.1 | PATCH | Ensure NIS Client is not installed"
  apt:
      name: nis
      state: absent
  when:
      - ubtu18cis_rule_2_3_1
      - not ubtu18cis_nis_required
  tags:
      - level1-server
      - level1-workstation
      - scored
      - rule_2.3.1
      - nis

- name: "SCORED | 2.3.2 | PATCH | Ensure rsh client is not installed"
  apt:
      name: rsh-client
      state: absent
  when:
      - ubtu18cis_rule_2_3_2
      - not ubtu18cis_rsh_required
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_2.3.2
      - rsh

- name: "SCORED | 2.3.3 | PATCH | Ensure talk client is not installed"
  apt:
      name: talk
      state: absent
  when:
      - ubtu18cis_rule_2_3_3
      - not ubtu18cis_talk_required
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_2.3.3
      - talk

- name: "SCORED | 2.3.4 | PATCH | Ensure telnet client is not installed"
  apt:
      name: telnet
      state: absent
  when:
      - ubtu18cis_rule_2_3_4
      - not ubtu18cis_telnet_required
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_2.3.4
      - telnet

- name: "SCORED | 2.3.5 | PATCH | Ensure LDAP client is not installed"
  apt:
      name: ldap-utils
      state: absent
  when:
      - ubtu18cis_rule_2_3_5
      - not ubtu18cis_ldap_clients_required
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_2.3.5
      - ldap