---
- name: "SCORED | 1.5.1 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "SCORED | 1.5.1 | AUDIT | Ensure permissions on bootloader config are configured | Check for Grub file"
        stat:
            path: /boot/grub/grub.cfg
        register: ubtu18cis_1_5_1_grub_cfg_status

      - name: "SCORED | 1.5.1 | PATCH | Ensure permissions on bootloader config are configured | Set permissions"
        file:
            path: /boot/grub/grub.cfg
            owner: root
            group: root
            mode: 0400
        when:
            - ubtu18cis_1_5_1_grub_cfg_status.stat.exists
  when:
      - ubtu18cis_rule_1_5_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.5.1
      - grub

# ---------------
# ---------------
# The RHEL7 based control for this does not use a valid module
# I need to research best way to set grub pw for Ubuntu using the
# grub-mkpasswd-pbkdf2 command and passing the data at the same time.
# ---------------
# ---------------
# - name: "SCORED | 1.5.2 | PATCH | Ensure bootloader password is set"
#   block:
#       - name: "SCORED | 1.5.2 | PATCH | Ensure bootloader password is set"
#         grub_crypt:
#             password: "{{ ubtu18cis_bootloader_password }}"
#         register: grub_pass

#       - debug: var=grub_pass

#   when:
#       - ubtu18cis_rule_1_5_2
#   tags:
#       - level1-server
#       - level1-workstation
#       - scored
#       - patch
#       - rule_1.5.2
#       - grub
#       - notimplemented

- name: "SCORED | 1.5.3 | PATCH | Ensure authentication required for single user mode"
  user:
      name: root
      password: "{{ ubtu18cis_root_pw }}"
  when:
      - ubtu18cis_rule_1_5_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.5.3
      - passwd

- name: "NOTSCORED | 1.5.4 | PATCH | Ensure interactive boot is not enabled"
  block:
      - name: "NOTSCORED | 1.5.4 | PATCH | Ensure interactive boot is not enabled | Check for interactive login setting"
        shell: grep "^PROMPT_FOR_CONFIRM=" /etc/sysconfig/boot
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_5_4_interactive_login_status

      - name: "NOTSCORED | 1.5.4 | PATCH | Ensure interactive boot is not enabled | Set interactive login to no"
        lineinfile:
            path: /etc/sysconfig/boot
            regexp: '^PROMPT_FOR_CONFIRM'
            line: 'PROMPT_FOR_CONFIRM="no"'
        when: "'PROMPT_FOR_CONFIRM' in ubtu18cis_1_5_4_interactive_login_status.stdout"
  when:
      - ubtu18cis_rule_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.5.4
      - interactive_boot