---
- name: "1.5.1 | AUDIT | Ensure XD/NX support is enabled"
  block:
      - name: "1.5.1 | AUDIT | Ensure XD/NX support is enabled | Find status of XD/NX"
        ansible.builtin.shell: "journalctl | grep 'protection: active'"
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_5_1_xdnx_status

      - name: "1.5.1 | AUDIT | Ensure XD/NX support is enabled | Alert if XD/NX is not enabled"
        ansible.builtin.debug:
            msg:
                - "Warning!! You do not have XD/NX (Execute Disable/No Execute) enabled"
                - "To conform to CIS standards this needs to be enabled"
        when: "'active' not in ubtu18cis_1_5_1_xdnx_status.stdout"

      - name: "1.5.1 | AUDIT | Ensure XD/NX support is enabled. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.5.1'
  when:
      - ubtu18cis_rule_1_5_1
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.5.1
      - xd/nx

- name: "1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  block:
      - name: "1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set ASLR settings"
        ansible.builtin.lineinfile:
            path: /etc/sysctl.conf
            regexp: '^kernel.randomize_va_space'
            line: 'kernel.randomize_va_space = 2'

      - name: "1.5.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
        ansible.posix.sysctl:
            name: kernel.randomize_va_space
            value: '2'
  when:
      - ubtu18cis_rule_1_5_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.2
      - aslr

- name: "1.5.3 | PATCH | Ensure prelink is disabled"
  block:
      - name: "1.5.3 | PATCH | Ensure prelink is disabled | Restore binaries to normal"
        ansible.builtin.shell: prelink -ua
        changed_when: false
        failed_when: false

      - name: "1.5.3 | PATCH | Ensure prelink is disabled | Remove prelink package"
        ansible.builtin.package:
            name: prelink
            state: absent
  when:
      - ubtu18cis_rule_1_5_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.3
      - prelink

- name: "1.5.4 | PATCH | Ensure core dumps are restricted"
  block:
      - name: "1.5.4 | PATCH | Ensure core dumps are restricted"
        ansible.builtin.lineinfile:
            path: /etc/security/limits.conf
            regexp: '^#?\\*.*core'
            line: '*                hard    core            0'
            insertbefore: '^# End of file'

      - name: "1.5.4 | PATCH | Ensure core dumps are restricted"
        ansible.posix.sysctl:
            name: fs.suid_dumpable
            value: '0'
            state: present
            reload: true
            sysctl_set: true
            ignoreerrors: true
  when:
      - ubtu18cis_rule_1_5_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.5.4
      - coredump
