---
- name: "SCORED | 1.3.1 | PATCH | Ensure sudo is installed"
  apt:
      name: "{{ ubtu18cis_sudo_package }}"
      state: present
  when:
      - ubtu18cis_rule_1_3_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.3.1
      - sudo

- name: "SCORED | 1.3.2 | PATCH | Ensure sudo commands use pty"
  lineinfile:
      path: /etc/sudoers
      regexp: '^Defaults        use_'
      line: 'Defaults        use_pty'
      insertafter: '^Defaults'
  when:
      - ubtu18cis_rule_1_3_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.3.2
      - sudo

- name: "SCORED | 1.3.3 | PATCH | Ensure sudo log file exists"
  lineinfile:
      path: /etc/sudoers
      regexp: '^Defaults        logfile'
      line: 'Defaults        logfile="{{ ubtu18cis_sudo_logfile }}"'
      insertafter: '^Defaults'
  when:
      - ubtu18cis_rule_1_3_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.3.3
      - sudo
