---

- name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/cramfs.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: install cramfs /bin/true
            create: true

      - name: "1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Disable cramfs"
        community.general.modprobe:
            name: cramfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.1
      - cramfs

- name: "1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled"
  block:
      - name: "1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/freevxfs.conf
            regexp: "^(#)?install freevxfs(\\s|$)"
            line: install freevxfs /bin/true
            create: true

      - name: "1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled | Disable freevxfs"
        community.general.modprobe:
            name: freevxfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.2
      - freevxfs

- name: "1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled"
  block:
      - name: "1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/jffs2.conf
            regexp: "^(#)?install jffs2(\\s|$)"
            line: install jffs2 /bin/true
            create: true

      - name: "1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled | Disable jffs2"
        community.general.modprobe:
            name: jffs2
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.3
      - jffs2

- name: "1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled"
  block:
      - name: "1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/hfs.conf
            regexp: "^(#)?install hfs(\\s|$)"
            line: install hfs /bin/true
            create: true

      - name: "1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled | Disable hfs"
        community.general.modprobe:
            name: hfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.4
      - hfs

- name: "1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled"
  block:
      - name: "1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/hfsplus.conf
            regexp: "^(#)?install hfsplus(\\s|$)"
            line: install hfsplus /bin/true
            create: true

      - name: "1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Disable hfsplus"
        community.general.modprobe:
            name: hfsplus
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.5
      - hfsplus

- name: "1.1.1.6 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.6 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/udf.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: install udf /bin/true
            create: true

      - name: "1.1.1.6 | PATCH | Ensure mounting of udf filesystems is disabled | Disable udf"
        community.general.modprobe:
            name: udf
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.1.6
      - udf

- name: "1.1.2 | PATCH | Ensure /tmp is configured"
  ansible.posix.mount:
      path: /tmp
      src: /tmp
      state: mounted
      fstype: tmpfs
  when:
      - ubtu18cis_rule_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.2
      - tmp

- name: |
    "1.1.3 | PATCH | Ensure nodev option set on /tmp partition"
    "1.1.4 | PATCH | Ensure nosuid option set on /tmp partition"
    "1.1.5 | PATCH | Ensure noexec option set on /tmp partition"
  ansible.posix.mount:
      name: /tmp
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "defaults,{% if ubtu18cis_rule_1_1_3 %}nodev,{% endif %}{% if ubtu18cis_rule_1_1_4 %}nosuid,{% endif %}{% if ubtu18cis_rule_1_1_5 %}noexec{% endif %}"
  loop: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - ubtu18cis_rule_1_1_3 or
        ubtu18cis_rule_1_1_4 or
        ubtu18cis_rule_1_1_5
      - item.mount == '/tmp'
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5
      - tmp

- name: "1.1.6 | PATCH | Ensure /dev/shm is configured"
  ansible.posix.mount:
      path: /dev/shm
      src: /dev/shm
      state: mounted
      fstype: tmpfs
  when:
      - ubtu18cis_rule_1_1_6
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.6
      - tmp

- name: |
    "1.1.7 | PATCH | Ensure nodev option set on /dev/shm partition"
    "1.1.8 | PATCH | Ensure nosuid option set on /dev/shm partition"
    "1.1.9 | PATCH | Ensure noexec option set on /dev/shm partition"
  ansible.posix.mount:
      name: /dev/shm
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "defaults,{% if ubtu18cis_rule_1_1_7 %}nodev,{% endif %}{% if ubtu18cis_rule_1_1_8 %}nosuid,{% endif %}{% if ubtu18cis_rule_1_1_9 %}noexec{% endif %}"
  loop: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  notify: Remount shm
  when:
      - ubtu18cis_rule_1_1_7 or
        ubtu18cis_rule_1_1_8 or
        ubtu18cis_rule_1_1_9
      - item.mount == '/dev/shm'
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.7
      - rule_1.1.8
      - rule_1.1.9
      - /dev/shm

- name: "1.1.10 | AUDIT | Ensure separate partition exists for /var"
  block:
      - name: "1.1.10 | AUDIT | Ensure separate partition exists for /var | Gather /var partition"
        ansible.builtin.shell: mount | grep "on /var "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_10_var_mounted

      - name: "1.1.10 | AUDIT | Ensure separate partition exists for /var | Alert if /var partition does not exist"
        ansible.builtin.debug:
            msg:
                - "Warning!! There is no separate partition for /var"
                - "Please create a separate partition for /var"
        when:
            - ubtu18cis_1_1_10_var_mounted.stdout is not defined or
              ubtu18cis_1_1_10_var_mounted.stdout | length == 0

      - name: "1.1.10 | AUDIT | Ensure separate partition exists for /var | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.10'
        when:
            - ubtu18cis_1_1_10_var_mounted.stdout is not defined or
              ubtu18cis_1_1_10_var_mounted.stdout | length == 0
  when:
      - ubtu18cis_rule_1_1_10
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.10
      - var

- name: "1.1.11 | AUDIT | Ensure separate partition exists for /var/tmp"
  block:
      - name: "1.1.11 | AUDIT | Ensure separate partition exists for /var/tmp | Gather /var/tmp partition"
        ansible.builtin.shell: mount | grep "on /var/tmp "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_11_var_tmp_mounted

      - name: "1.1.11 | AUDIT | Ensure separate partition exists for /var/tmp | Alert if /var/tmp partition does not exist"
        ansible.builtin.debug:
            msg:
                - "Warning!! There is no separate partition for /var/tmp"
                - "Please create a separate partition for /var/tmp"
        when:
            - ubtu18cis_1_1_11_var_tmp_mounted.stdout is not defined or
              ubtu18cis_1_1_11_var_tmp_mounted.stdout | length == 0

      - name: "1.1.11 | AUDIT | Ensure separate partition exists for /var/tmp | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.11'
        when:
            - ubtu18cis_1_1_11_var_tmp_mounted.stdout is not defined or
              ubtu18cis_1_1_11_var_tmp_mounted.stdout | length == 0
  when:
      - ubtu18cis_rule_1_1_11
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.11
      - var/tmp

- name: |
    "1.1.12 | PATCH | Ensure nodev option set on /var/tmp partition"
    "1.1.13 | PATCH | Ensure nosuid option set on /var/tmp partition"
    "1.1.14 | PATCH | Ensure noexec option set on /var/tmp partition"
  ansible.posix.mount:
      name: /var/tmp
      src: "{{ item.device }}"
      state: present
      fstype: "{{ item.fstype }}"
      opts: "defaults,{% if ubtu18cis_rule_1_1_12 %}nodev,{% endif %}{% if ubtu18cis_rule_1_1_13 %}nosuid,{% endif %}{% if ubtu18cis_rule_1_1_14 %}noexec{% endif %}"
  loop: "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  notify: Remount var_tmp
  when:
      - ubtu18cis_rule_1_1_12 or
        ubtu18cis_rule_1_1_13 or
        ubtu18cis_rule_1_1_14
      - item.mount == '/var/tmp'
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.12
      - rule_1.1.13
      - rule_1.1.14
      - var_tmp

- name: "1.1.15 | AUDIT | Ensure separate partition exists for /var/log"
  block:
      - name: "1.1.15 | AUDIT | Ensure separate partition exists for /var/log | Gather /var/log partition"
        ansible.builtin.shell: mount | grep "on /var/log "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_15_var_log_mounted

      - name: "1.1.15 | AUDIT | Ensure separate partition exists for /var/log | Alert if /var/log partition does not exist"
        ansible.builtin.debug:
            msg:
                - "Warning!! There is no separate partition for /var/log"
                - "Please create a separate partition for /var/log"
        when:
            - ubtu18cis_1_1_15_var_log_mounted.stdout is not defined or
              ubtu18cis_1_1_15_var_log_mounted.stdout | length == 0

      - name: "1.1.15 | AUDIT | Ensure separate partition exists for /var/log | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.15'
        when:
            - ubtu18cis_1_1_15_var_log_mounted.stdout is not defined or
              ubtu18cis_1_1_15_var_log_mounted.stdout | length == 0
  when:
      - ubtu18cis_rule_1_1_15
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.15
      - var_log

- name: "1.1.16 | AUDIT | Ensure separate partition exists for /var/log/audit"
  block:
      - name: "1.1.16 | AUDIT | Ensure separate partition exists for /var/log/audit | Gather /var/log/audit"
        ansible.builtin.shell: mount | grep "on /var/log/audit "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_16_var_log_audit_mounted

      - name: "1.1.16 | AUDIT | Ensure separate partition exists for /var/log/audit | Alert if /var/log/audit partition does not exist."
        ansible.builtin.debug:
            msg:
                - "Warning!! There is no separate partition for /var/log/audit"
                - "Please create a separate partition for /var/log/audit"
        when:
            - ubtu18cis_1_1_16_var_log_audit_mounted.stdout is not defined or
              ubtu18cis_1_1_16_var_log_audit_mounted.stdout | length == 0

      - name: "1.1.16 | AUDIT | Ensure separate partition exists for /var/log/audit | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.16'
        when:
            - ubtu18cis_1_1_16_var_log_audit_mounted.stdout is not defined or
              ubtu18cis_1_1_16_var_log_audit_mounted.stdout | length == 0
  when:
      - ubtu18cis_rule_1_1_16
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.16
      - var_log_audit

- name: "1.1.17 | AUDIT | Ensure separate partition exists for /home."
  block:
      - name: "1.1.17 | AUDIT | Ensure separate partition exists for /home | Gather /home."
        ansible.builtin.shell: mount | grep "on /home"
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_17_home_mounted

      - name: "1.1.17 | AUDIT | Ensure separate partition exists for /home | Alert if /home partition does not exist."
        ansible.builtin.debug:
            msg:
                - "Warning!! There is no separate partition for /home"
                - "Please create a separate partition for /home"
        when:
            - ubtu18cis_1_1_17_home_mounted.stdout is not defined or
              ubtu18cis_1_1_17_home_mounted.stdout | length == 0

      - name: "1.1.17 | AUDIT | Ensure separate partition exists for /home | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.17'
        when:
            - ubtu18cis_1_1_17_home_mounted.stdout is not defined or
              ubtu18cis_1_1_17_home_mounted.stdout | length == 0
  when:
      - ubtu18cis_rule_1_1_17
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.17
      - /home

- name: "1.1.18 | PATCH | Ensure /home partition includes the nodev option."
  ansible.posix.mount:
      name: "/home"
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "nodev"
  with_items: "{{ ansible_mounts }}"
  when:
      - ubtu18cis_rule_1_1_18
      - item.mount == "/home"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.18
      - /home

- name: "1.1.19 | AUDIT | Ensure nodev option set on removable media partitions."
  block:
      - name: "1.1.19 | AUDIT | Ensure nodev option set on removable media partitions. | Warning Messsage."
        ansible.builtin.debug:
            msg: "Warning!! Ensure nodev option set on removable media partitions."

      - name: "1.1.19 | AUDIT | Ensure nodev option set on removable media partitions. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.19'
  when:
      - ubtu18cis_rule_1_1_19
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.1.19
      - removable_media

- name: "1.1.20 | AUDIT | Ensure nosuid option set on removable media partitions."
  block:
      - name: "1.1.20 | AUDIT | Ensure nosuid option set on removable media partitions. | Warning Message."
        ansible.builtin.debug:
            msg: "Warning!! Ensure nosuid option set on removable media partitions."

      - name: "1.1.20 | AUDIT | Ensure nosuid option set on removable media partitions. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.20'
  when:
      - ubtu18cis_rule_1_1_20
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.1.20
      - removable_media

- name: "1.1.21 | AUDIT | Ensure noexec option set on removable media partitions."
  block:
      - name: "1.1.21 | AUDIT | Ensure noexec option set on removable media partitions. | Warning Message."
        ansible.builtin.debug:
            msg: "Warning!! Ensure noexec option set on removable media partitions."

      - name: "1.1.21 | AUDIT | Ensure noexec option set on removable media partitions. | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.1.21'
  when:
      - ubtu18cis_rule_1_1_21
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_1.1.21
      - removable_media

- name: "1.1.22 | PATCH | Ensure sticky bit is set on all world-writable directories"
  ansible.builtin.shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null | xargs -I '{}' chmod a+t '{}'
  failed_when: ubtu18cis_1_1_22_status.rc > 0
  register: ubtu18cis_1_1_22_status
  when:
      - ubtu18cis_rule_1_1_22
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.22
      - sticky_bit

- name: "1.1.23 | PATCH | Disable Automounting"
  ansible.builtin.service:
      name: autofs
      state: stopped
      enabled: false
  when:
      - ubtu18cis_rule_1_1_23
      - ubtu18cis_autofs_service_status.stdout == "loaded"
      - not ubtu18cis_allow_autofs
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.23
      - automounting

- name: "1.1.24 | PATCH | Disable USB Storage"
  block:
      - name: "1.1.24 | PATCH | Disable USB Storage | Set modprobe config"
        ansible.builtin.lineinfile:
            path: /etc/modprobe.d/usb_storage.conf
            regexp: '^install usb-storage'
            line: 'install usb-storage /bin/true'
            create: true

      - name: "1.1.24 | PATCH | Disable USB Storage | Remove usb-storage module"
        community.general.modprobe:
            name: usb-storage
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_24
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_1.1.24
      - usb_storage
