---
- name: "SCORED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/cramfs.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: install cramfs /bin/true
            create: yes

      - name: "SCORED | 1.1.1.1 | PATCH | Ensure mounting of cramfs filesystems is disabled | Disable cramfs"
        modprobe:
            name: cramfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.1
      - cramfs

- name: "SCORED | 1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/freevxfs.conf
            regexp: "^(#)?install freevxfs(\\s|$)"
            line: install freevxfs /bin/true
            create: yes

      - name: "SCORED | 1.1.1.2 | PATCH | Ensure mounting of freevxfs filesystems is disabled | Disable freevxfs"
        modprobe:
            name: freevxfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.2
      - freevxfs

- name: "SCORED | 1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/jffs2.conf
            regexp: "^(#)?install jffs2(\\s|$)"
            line: install jffs2 /bin/true
            create: yes

      - name: "SCORED | 1.1.1.3 | PATCH | Ensure mounting of jffs2 filesystems is disabled | Disable jffs2"
        modprobe:
            name: jffs2
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.3
      - jffs2

- name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/hfs.conf
            regexp: "^(#)?install hfs(\\s|$)"
            line: install hfs /bin/true
            create: yes

      - name: "SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled | Disable hfs"
        modprobe:
            name: hfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.4
      - hfs

- name: "SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/hfsplus.conf
            regexp: "^(#)?install hfsplus(\\s|$)"
            line: install hfsplus /bin/true
            create: yes

      - name: "SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled | Disable hfsplus"
        modprobe:
            name: hfsplus
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_5
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.5
      - hfsplus

- name: "SCORED | 1.1.1.6 | PATCH | Ensure mounting of squashfs filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.6 | PATCH | Ensure mounting of squashfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/squashfs.conf
            regexp: "^(#)?install squashfs(\\s|$)"
            line: install squashfs /bin/true
            create: yes

      - name: "SCORED | 1.1.1.6 | PATCH | Ensure mounting of squashfs filesystems is disabled | Disable squashfs"
        modprobe:
            name: squashfs
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_6
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.6
      - squashfs

- name: "SCORED | 1.1.1.7 | PATCH | Ensure mounting of udf filesystems is disabled"
  block:
      - name: "SCORED | 1.1.1.7 | PATCH | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/udf.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: install udf /bin/true
            create: yes

      - name: "SCORED | 1.1.1.7 | PATCH | Ensure mounting of udf filesystems is disabled | Disable udf"
        modprobe:
            name: udf
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_7
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.1.7
      - udf

- name: "NOTSCORED | 1.1.1.8 | PATCH | Ensure mounting of FAT filesystems is limited"
  block:
      - name: "NOTSCORED | 1.1.1.8 | PATCH | Ensure mounting of FAT filesystems is limited | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/vfat.conf
            regexp: "^(#)?install vfat(\\s|$)"
            line: install vfat /bin/true
            create: yes

      - name: "NOTSCORED | 1.1.1.8 | PATCH | Ensure mounting of FAT filesystems is limited | Disable FAT"
        modprobe:
            name: vfat
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_1_8
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - patch
      - rule_1.1.1.8
      - vfat

- name: "SCORED | 1.1.2 | PATCH | Ensure /tmp is configured"
  mount:
      path: /tmp
      src: /tmp
      state: mounted
      fstype: tmpfs
      opts: "{{ ubtu18cis_tmp_fstab_options }}"
  when:
      - ubtu18cis_rule_1_1_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.2
      - tmp

- name: |
    "SCORED | 1.1.3 | PATCH | Ensure nodev option set on /tmp partition"
    "SCORED | 1.1.4 | PATCH | Ensure nosuid option set on /tmp partition"
    "SCORED | 1.1.5 | PATCH | Ensure noexec option set on /tmp partition"
  mount:
      name: /tmp
      src: /tmp
      state: remounted
      fstype: tmpfs
      opts: "{{ ubtu18cis_tmp_fstab_options }}"
  when:
      - ubtu18cis_rule_1_1_3 or
        ubtu18cis_rule_1_1_4 or
        ubtu18cis_rule_1_1_5
      - ubtu18cis_vartmp['enabled']
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.3
      - rule_1.1.4
      - rule_1.1.5
      - tmp

- name: "SCORED | 1.1.6 | AUDIT | Ensure separate partition exists for /var"
  block:
      - name: "SCORED | 1.1.6 | AUDIT | Ensure separate partition exists for /var | Gather /var partition"
        shell: mount | grep "on /var "
        changed_when: false
        failed_when: false
        args:
            warn: false
        register: ubtu18cis_1_1_6_var_mounted

      - name: "SCORED | 1.1.6 | AUDIT | Ensure separate partition exists for /var | Alert if /var partition does not exist"
        debug:
            msg:
                - "ALERT!!!! There is no separate partition for /var"
                - "Please create a separate partition for /var"
        when: ubtu18cis_1_1_6_var_mounted.stdout == ""
  when:
      - ubtu18cis_rule_1_1_6
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - rule_1.1.6
      - var

- name: "SCORED | 1.1.7 | AUDIT | Ensure separate partition exists for /var/tmp"
  block:
      - name: "SCORED | 1.1.7 | AUDIT | Ensure separate partition exists for /var/tmp | Gather /var/tmp partition"
        shell: mount | grep "on /var/tmp "
        changed_when: false
        failed_when: false
        args:
            warn: false
        register: ubtu18cis_1_1_7_var_tmp_mounted

      - name: "SCORED | 1.1.7 | AUDIT | Ensure separate partition exists for /var/tmp | Alert if /var/tmp partition does not exist"
        debug:
            msg:
                - "ALERT!!!! There is no separate partition for /var/tmp"
                - "Please create a separate partition for /var/tmp"
        when: ubtu18cis_1_1_7_var_tmp_mounted.stdout == ""
  when:
      - ubtu18cis_rule_1_1_7
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - rule_1.1.7
      - var/tmp

- name: |
    "SCORED | 1.1.8 | PATCH | Ensure nodev option set on /var/tmp partition"
    "SCORED | 1.1.9 | PATCH | Ensure nosuid option set on /var/tmp partition"
    "SCORED | 1.1.10 | PATCH | Ensure noexec option set on /var/tmp partition"
  mount:
      name: /var/tmp
      src: "{{ ubtu18cis_vartmp['source'] }}"
      state: present
      fstype: "{{ ubtu18cis_vartmp['fstype'] }}"
      opts: "{{ ubtu18cis_vartmp['opts'] }}"

  when:
      - ubtu18cis_rule_1_1_8 or
        ubtu18cis_rule_1_1_9 or
        ubtu18cis_rule_1_1_10
      - ubtu18cis_vartmp['enabled']
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.8
      - rule_1.1.9
      - rule_1.1.10
      - var/tmp

- name: "SCORED | 1.1.11 | AUDIT | Ensure separate partition exists for /var/log"
  block:
      - name: "SCORED | 1.1.11 | AUDIT | Ensure separate partition exists for /var/log | Gather /var/log partition"
        shell: mount | grep "on /var/log "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_11_var_log_mounted
        args:
            warn: false

      - name: "SCORED | 1.1.11 | AUDIT | Ensure separate partition exists for /var/log | Alert if /var/log partition does not exist"
        debug:
            msg:
                - "ALERT!!!! There is no separate partition for /var/log"
                - "Please create a separate partition for /var/log"
        when: ubtu18cis_1_1_11_var_log_mounted.stdout == ""
  when:
      - ubtu18cis_rule_1_1_11
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - rule_1.1.11
      - var/log

- name: "SCORED | 1.1.12 | AUDIT | Ensure separate partition exists for /var/log/audit"
  block:
      - name: "SCORED | 1.1.12 | AUDIT | Ensure separate partition exists for /var/log/audit | Gather /var/log/audit"
        shell: mount | grep "on /var/log/audit "
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_12_var_log_audit_mounted
        args:
            warn: false

      - name: "SCORED | 1.1.12 | AUDIT | Ensure separate partition exists for /var/log/audit | Alert if /var/log/audit partition does not exist"
        debug:
            msg:
                - "ALERT!!!! There is no separate partition for /var/log/audit"
                - "Please create a separate partition for /var/log/audit"
        when: ubtu18cis_1_1_12_var_log_audit_mounted.stdout == ""
  when:
      - ubtu18cis_rule_1_1_12
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - var/log/audit

- name: "SCORED | 1.1.13 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "SCORED | 1.1.13 | AUDIT | Ensure separate partition exists for /home | Gather /home"
        shell: mount | grep "on /home"
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_1_13_home_mounted
        args:
            warn: false

      - name: "SCORED | 1.1.13 | AUDIT | Ensure separate partition exists for /home | Alert if /home partition does not exist"
        debug:
            msg:
                - "ALERT!!!! There is no separate partition for /home"
                - "Please create a separate partition for /home"
        when: ubtu18cis_1_1_13_home_mounted.stdout == ""
  when:
      - ubtu18cis_rule_1_1_13
  tags:
      - level2-server
      - level2-workstation
      - scored
      - audit
      - /home

- name: "SCORED | 1.1.14 | PATCH | Ensure nodev option set on /home partition"
  mount:
      name: "/home"
      src: "{{ item.device }}"
      state: mounted
      fstype: "{{ item.fstype }}"
      opts: "nodev"
  with_items: "{{ ansible_mounts }}"
  when:
      - ubtu18cis_rule_1_1_14
      - item.mount == "/home"
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.14
      - /home

- name: |
    "SCORED | 1.1.15 | PATCH | Ensure nodev option set on /dev/shm partition"
    "SCORED | 1.1.16 | PATCH | Ensure nosuid option set on /dev/shm partition"
    "SCORED | 1.1.17 | PATCH | Ensure noexec option set on /dev/shm partition"
  mount:
      name: /dev/shm
      src: tmpfs
      state: mounted
      fstype: tmpfs
      opts: "defaults,nodev,nosuid,noexec"
  when:
      - ubtu18cis_rule_1_1_15 or
        ubtu18cis_rule_1_1_16 or
        ubtu18cis_rule_1_1_17
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.15
      - rule_1.1.16
      - rule_1.1.17
      - /dev/shm

- name: "NOTSCORED | 1.1.18 | AUDIT | Ensure nodev option set on removable media partitions"
  debug:
      msg: "Warning!!!! Not relevent control"
  when:
      - ubtu18cis_rule_1_1_18
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - audit
      - rule_1.1.18
      - removable_media

- name: "NOTSCORED | 1.1.19 | AUDIT | Ensure nosuid option set on removable media partitions"
  debug:
      msg: "Warning!!!! Not relevent control"
  when:
      - ubtu18cis_rule_1_1_19
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - audit
      - rule_1.1.19
      - removable_media

- name: "NOTSCORED | 1.1.20 | AUDIT | Ensure noexec option set on removable media partitions"
  debug:
      msg: "Warning!!!! Not relevent control"
  when:
      - ubtu18cis_rule_1_1_20
  tags:
      - level1-server
      - level1-workstation
      - notscored
      - audit
      - rule_1.1.20
      - removable_media

- name: "SCORED | 1.1.21 | PATCH | Ensure sticky bit is set on all world-writable directories"
  shell: df --local -P | awk '{if (NR!=1) print $6}' | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null | xargs -I '{}' chmod a+t '{}'
  failed_when: ubtu18cis_1_1_21_status.rc>0
  register: ubtu18cis_1_1_21_status
  when:
      - ubtu18cis_rule_1_1_21
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.21
      - sticky_bit

- name: "SCORED | 1.1.22 | PATCH | Disable Automounting"
  service:
      name: autofs
      state: stopped
      enabled: no
  when:
      - ubtu18cis_rule_1_1_22
      - ubtu18cis_autofs_service_status.stdout == "loaded"
      - not ubtu18cis_allow_autofs
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.1.22
      - automounting

- name: "SCORED | 1.1.23 | PATCH | Disable USB Storage"
  block:
      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Set modprobe config"
        lineinfile:
            path: /etc/modprobe.d/usb_storage.conf
            regexp: '^install usb-storage'
            line: 'install usb-storage /bin/true'
            create: yes

      - name: "SCORED | 1.1.23 | PATCH | Disable USB Storage | Remove usb-storage module"
        modprobe:
            name: usb-storage
            state: absent
        when: ansible_connection != 'docker'
  when:
      - ubtu18cis_rule_1_1_23
  tags:
      - level1-server
      - level2-workstation
      - scored
      - patch
      - rule_1.1.23
      - usb_storage
