---
- name: "SCORED | 1.6.1 | AUDIT | Ensure XD/NX support is enabled"
  block:
      - name: "SCORED | 1.6.1 | AUDIT | Ensure XD/NX support is enabled | Find status of XD/NX"
        shell: "journalctl | grep 'protection: active'"
        changed_when: false
        failed_when: false
        register: ubtu18cis_1_6_1_xdnx_status

      - name: "SCORED | 1.6.1 | AUDIT | Ensure XD/NX support is enabled | Alert if XD/NX is not enabled"
        debug:
            msg:
                - "ALERT!!!!You do not have XD/NX (Execute Disable/No Execute) enabled"
                - "To conform to CIS standards this needs to be enabled"
        when: "'active' not in ubtu18cis_1_6_1_xdnx_status.stdout"
  when:
      - ubtu18cis_rule_1_6_1
  tags:
      - level1-server
      - level1-workstation
      - scored
      - audit
      - rule_1.6.1
      - xd/nx

- name: "SCORED | 1.6.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled"
  block:
      - name: "SCORED | 1.6.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set ASLR settings"
        lineinfile:
            path: /etc/sysctl.conf
            regexp: '^kernel.randomize_va_space'
            line: 'kernel.randomize_va_space = 2'

      - name: "SCORED | 1.6.2 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
        sysctl:
            name: kernel.randomize_va_space
            value: '2'
  when:
      - ubtu18cis_rule_1_6_2
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.6.2
      - aslr

- name: "SCORED | 1.6.3 | PATCH | Ensure prelink is disabled"
  block:
      - name: "SCORED | 1.6.3 | PATCH | Ensure prelink is disabled | Restore binaries to normal"
        command: prelink -ua
        changed_when: false
        failed_when: false

      - name: "SCORED | 1.6.3 | PATCH | Ensure prelink is disabled | Remove prelink package"
        apt:
            name: prelink
            state: absent
  when:
      - ubtu18cis_rule_1_6_3
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.6.3
      - prelink

- name: "SCORED | 1.6.4 | PATCH | Ensure core dumps are restricted"
  block:
      - name: "SCORED | 1.6.4 | PATCH | Ensure core dumps are restricted"
        lineinfile:
            path: /etc/security/limits.conf
            regexp: '^#?\\*.*core'
            line: '*                hard    core            0'
            insertbefore: '^# End of file'

      - name: "SCORED | 1.6.4 | PATCH | Ensure core dumps are restricted"
        sysctl:
            name: fs.suid_dumpable
            value: '0'
            state: present
            reload: yes
            sysctl_set: yes
            ignoreerrors: yes
  when:
      - ubtu18cis_rule_1_6_4
  tags:
      - level1-server
      - level1-workstation
      - scored
      - patch
      - rule_1.6.4
      - coredump